# Generated by Django 5.0.6 on 2024-06-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('inicio', models.DateField(verbose_name='Inicio')),
                ('conclusao', models.DateField(verbose_name='Conclusao')),
                ('descricao', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
    ]
