# Generated by Django 5.0.6 on 2024-06-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefamodel',
            name='conclusao',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tarefamodel',
            name='inicio',
            field=models.DateField(blank=True),
        ),
    ]
